language: php

php:
- 7.4

before_script:
- composer install
- touch storage/logs/laravel.log

script:
- ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
