language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - CANONICAL_BASE=https://roelofjanelsinga.com APP_NAME=roelofjanelsinga APP_ENV=production

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - composer install
  - yarn
  - npm run prod
  - ./vendor/bin/phpunit
