name: PHPUnit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [7.4, 8.0]

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phpunit:9.5.0
          coverage: pcov
          extensions: mbstring
      - name: Install Composer dependencies
        run: composer install
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml\
      - name: Upload coverage reports
        run: bash <(curl -s https://codecov.io/bash)
